# Generated by Django 2.0.8 on 2018-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miesiac',
            name='numer',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
    ]
