# Generated by Django 2.1 on 2018-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miesiac',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
