# Generated by Django 2.0.7 on 2018-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0002_auto_20180812_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zakup',
            name='price',
            field=models.FloatField(default=0.1),
        ),
    ]
