# Generated by Django 2.0.8 on 2018-11-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0002_miesiac_numer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miesiac',
            name='numer',
        ),
    ]
