# Generated by Django 2.0.7 on 2018-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0004_auto_20180815_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
