# Generated by Django 2.0.7 on 2018-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0005_auto_20180815_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='miesiac',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='zakup',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
