# Generated by Django 2.0.7 on 2018-08-18 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0007_auto_20180818_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='month',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Miesiac'),
        ),
    ]
