# Generated by Django 2.0.7 on 2018-08-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0009_auto_20180818_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miesiac',
            name='number',
        ),
        migrations.AlterField(
            model_name='zakup',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Kategoria'),
        ),
    ]
