# Generated by Django 2.0.7 on 2018-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0011_auto_20180818_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakup',
            name='total',
            field=models.FloatField(default=0.1),
        ),
    ]
