# Generated by Django 2.0.8 on 2018-08-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0012_zakup_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='zakup',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Rok'),
        ),
    ]
