# Generated by Django 2.0.8 on 2018-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0014_auto_20180831_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rok',
            name='name',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
