# Generated by Django 2.0.8 on 2018-08-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0018_auto_20180831_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Miesiac'),
        ),
    ]
