# Generated by Django 2.0.8 on 2018-08-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0019_auto_20180831_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Rok'),
        ),
    ]
