# Generated by Django 2.0.7 on 2018-09-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0020_auto_20180831_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rok',
            name='name',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zakup',
            name='year',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Rok'),
        ),
    ]
