# Generated by Django 2.0.7 on 2018-09-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0022_auto_20180901_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakup',
            name='year',
        ),
        migrations.DeleteModel(
            name='Rok',
        ),
    ]
