# Generated by Django 2.0.7 on 2018-09-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0024_auto_20180901_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rok',
            old_name='name',
            new_name='year',
        ),
    ]
