# Generated by Django 2.0.7 on 2018-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0026_auto_20180901_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rok',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
