# Generated by Django 2.0.7 on 2018-09-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0029_auto_20180901_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakup',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
