# Generated by Django 2.0.7 on 2018-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0031_auto_20180901_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
