# Generated by Django 2.0.7 on 2018-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0036_auto_20180901_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
