# Generated by Django 2.0.7 on 2019-03-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0037_auto_20180901_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='month',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='homeb_app.Miesiac'),
        ),
        migrations.AlterField(
            model_name='zakup',
            name='year',
            field=models.IntegerField(),
        ),
    ]
