# Generated by Django 2.0.8 on 2018-09-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeb_app', '0042_auto_20180910_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
